export const DATA_INSERTED_INTO_DATABASE = 'DATA_INSERTED';
export const DATA_UPDATED_INTO_DATABASE = 'DATA_UPDATED';
export const DATA_DELETED_INTO_DATABASE = 'DATA_DELETED';
export const DATA_INQUIRED_FROM_DATABASE = 'DATA_INQUIRED';
