/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace task {
    export interface TaskService {
        create(
            data: CreateTaskRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Task>;
        findOne(
            data: FindOneRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Task>;
    }
    export interface CreateTaskRequest {
        title?: string;
        description?: string;
    }
    export interface Task {
        id?: number;
        title?: string;
        description?: string;
    }
    export interface FindOneRequest {
        id?: number;
    }
}

